### ISSUE TITLE
和videoplay一起使用滑动冲突 请问有解决方案吗

### ISSUE THREAD

**Issue by okayFan** [lmxjw3/clearscreen#1]

**Comment by lmxjw3** [comment]
videoplay已优化，请使用 implementation 'com.lmxjw3.media:videoplay:1.0.1'

**Comment by zhuoshirong** [comment]
recyclerview 设置水平滚动会有冲突

**Comment by lmxjw3** [comment]
> recyclerview 设置水平滚动会有冲突

这就是个水平滑动清屏的控件，recyclerview水平滚动肯定会冲突，关键是你要实现什么样的效果
