### ISSUE TITLE
点击按钮清屏

### ISSUE THREAD

**Issue by Newwaygo** [lmxjw3/clearscreen#2]
大佬，不用手滑动，而是用手点击某个清屏按钮，怎么清屏，还有切换直播间后，再切换回来怎么恢复没有清屏的状态

**Comment by lmxjw3** [comment]
加了4个方法，已经提交了

clearWithAnim 清屏（有动画）
clearWithoutAnim 清屏（无动画）
restoreWithAnim 还原（有动画）
restoreWithoutAnim 还原（无动画）
